config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'

  resources :posts do
    resources :comments
  end

  resource :likes, only: %i[create destroy]

  #VERB     URI PATTERN       CONTROLLER ACT        PREFIX           #
  get 'destroy/:id',  to: 'posts#destroy', as: 'delete_post',   method: :delete
  get 'posts/:id'   ,  to: 'posts#show'   , as: 'show_post'

  # get 'destroy/:id/like', to: 'likes#destroy', as: 'delete_like'
  get 'likes/:id'  ,   to: 'likes#create',  as: 'delete_like', method: :delete

  #     'update/:id'
  # get 'posts/:id' ,  to: 'posts#update' , as: 'update_post', method: :patch
  # not working as expected
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: %i[likeable_id likeable_type] }

  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new(likes_params)
    unless @like.save
      flash[:alert] = @like.errors.full_messages.to_sentence
    end

    redirect_back(fallback_location: '@like.post')
  end

  def destroy
    @like = current_user.likes.find(params[:id])
    likeable = @like.likeable

    @like.destroy
    redirect_back(fallback_location: '@like.post')
  end

  private

  def likes_params
    params.require(:like).permit(:likeable_id, :likeable_type)
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_comments_likings.html.erb
<% like = current_user.likes.find_by(likeable: likeable) %>
<% if like.nil? %>
      <%= button_to image_tag('like.svg', style: 'width:30px') , likes_path, params: { like: { likeable_id: likeable.id, likeable_type: likeable.class.to_s }}, method: :post %>
       <%#= button_to 'Like', likes_path, params: { like: { post_id: post.id }}, method: :post  %>
    <% else %>
      <%= button_to image_tag('liked_btn.svg', style: 'width: 30px'), { controller: 'likes', action: 'destroy', id: like.id },
                    method: :delete, data: { confirm: "Are you sure?" } %>
    <%= likeable.likes.count %>
<% end %>

app/views/likes/_likings.html.erb
<% like = current_user.likes.find_by(likeable: likeable) %>
<% if like.nil? %>
  <%= button_to image_tag('like.svg', style: 'width:30px') + "  Like", likes_path, params: { like: { likeable_id: likeable.id, likeable_type: likeable.class.to_s }}, method: :post %>
   <%#= button_to 'Like', likes_path, params: { like: { post_id: post.id }}, method: :post  %>
<% else %>
  <%= button_to image_tag('liked_btn.svg', style: 'width: 30px') + " Unlike", { controller: 'likes', action: 'destroy', id: like.id },
                method: :delete, data: { confirm: "Are you sure?" } %>
<% end %>