config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'

  resources :posts do
    resources :comments
  end

  resource :likes, only: %i[create destroy]

  #VERB     URI PATTERN       CONTROLLER ACT        PREFIX           #
  get 'destroy/:id',  to: 'posts#destroy', as: 'delete_post',   method: :delete
  get 'posts/:id'   ,  to: 'posts#show'   , as: 'show_post'

  # get 'destroy/:id/like', to: 'likes#destroy', as: 'delete_like'
  get 'likes/:id'  ,   to: 'likes#create',  as: 'delete_like', method: :delete

  #     'update/:id'
  # get 'posts/:id' ,  to: 'posts#update' , as: 'update_post', method: :patch
  # not working as expected
end

app/models/post.rb
class Post < ApplicationRecord
  include Visible

  # def liked?(user)
  #   !!self.likes.find{|like| like.user_id == user.id }
  # end

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy

  validates :description, presence: true, length: { minimum: 5 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[show edit update destroy]

  # before_action :is_public?, only: [:status]

  def index
    @posts = Post.all.order(id: :desc)
  end

  def edit; end

  def show
    @comments = @post.comments
  end

  def create
    @post = Post.new(post_params)

    # @status = @post.status.public?

    @post.user_id = current_user.id
    # render plain: @post
    respond_to do |format|
      if @post.save
        format.html { redirect_back(fallback_location: post_url(@post), notice: 'Post was successfully created!') }
        # format.json { render :show, status: :created, location: @post }
      else
        format.html { render :index, status: :unprocessable_entity }
        # format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated!' }
        # format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        # format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_path, notice: 'Post was successfully deleted!' }
      # format.json { head :no_content }
    end
  end

  private

  # def is_public?
  #   unless VALID_STATUSES.display?
  #     redirect_to :back
  #   end
  # end

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:description, :status)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_all_posts.html.erb
<style>
  button {
      border: none;
      background-color: #ffffff;
  }
</style>

<% @posts.each do |post| %>
  <% if post.public? || post.user.id == current_user.id %>
  <br>
  <div style="background-color: #ffffff; border-radius: 17px">
    <div style="padding: 30px;">
        <div class="text-muted"> <!-- heading nahi banana hai (post_title)-->
          <h5><%= image_tag('maze_logo.svg', style: 'margin-right:1rem') %>
              <%= post.user.first_name %></h5>
          <small>
            <%= time_ago_in_words(post.created_at) %> ago
            <small>&#8226</small>
            <%= post.status.to_str %>
            <%#= time_tag post.created_at, "data-local": "time-ago" %>
          </small>
          <%= render 'posts/three_dots_dropdown', post: post %>
        </div>
      <br>
      <div>
        <p class="sed"><!--post_description-->
          <%= post.description %>
        </p>
      </div>
    </div>
    <br>
    <div style="margin-left: 32px; color: #60616599">
      <!--likes-->
      <%#= if @post.likes.nil? @post.likes =0 else @post.likes end  %>
      <%#= post.likes.count %> <%#= (post.likes.count) == 1 ? 'Like' : 'Likes'%>

      <small><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></small>
      <small>&#8226</small>
      <small><%= render 'comments/comment_count', post: post %></small>
    </div>
    <hr class="des"><!---------------------------------------------->
    <div class="d-flex" style="margin-left: 30px;">
      <!--like_btn-->
      <%= render 'likes/likings', likeable: post %>
      <!--comment_btn-->
      <span style='margin-left: 15rem;' >
        <%= link_to image_tag('comment.svg', style: 'width:30px') + "  Comments", show_post_path(post) %>
      </span>
    </div>
    <hr class="des"><!---------------------------------------------->

    <div class="container-fluid">
      <div class style="padding: 10px">
        <%= render 'comments/comment_menubar', post: post %><br>

        <% post.comments.order(created_at: :desc).each do |comment| %>
            <%= render 'comments/comment_content', post: post, comment: comment %>
            <% break %>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
<% end %>

app/views/posts/_post_menu.html.erb
<style>
  select {
      margin-right: 1rem;
      border: none;
      background-color: #F9FAFB;
      border-radius: 10px;
      outline-color: #F7F7F7;
      color: #666666;
  }

</style>


<div style="padding: inherit; border-radius: inherit; background-color: #FFFFFF" class="container-fluid">
    <%= form_with scope: :post, url: posts_path, local: true do |post| %>
      <p>
    <!--placeholder what's Happening-->
      <%= post.text_area( :description, { class: 'form-control',  :placeholder => "What's happening ?", style: 'background-color:#F5F6F8; border-radius: 17px; border-color:#F5F6F8', rows:1 }) %>

      </p>
      <p>
        <div style="float: right;">
            <!--post_btn--><!--float:right--><!--<%#= post.label :status %><br>-->

          <%= post.select :status, ['public', 'private'], selected: 'public', class:'dropdown-menu' %>
          <%= post.submit '  Post  ', class:'btn btn-primary'%>
        </div>
      <% end %>

          <div class="btn">
            <!--live video btn-->
            <%= link_to image_tag('live_video.png') %>
          </div>
          <div class="btn">
            <!--photo/video btn-->
            <%= link_to image_tag('Photo_video.png') %>
          </div>
          <div class="btn">
            <!--feeling btn-->
            &nbsp;&nbsp;<%= link_to image_tag('Smiley.png') %>
          </div>
        </p>
    </div>

app/views/posts/_three_dots_dropdown.html.erb
  <% if  current_user.id == post.user.id  %>
    <span style="float: right;">
      <div class="dropdown-container" tabindex="-1">
        <div class="three-dots"></div>
        <div class="dropdown">
          <%= link_to 'Show', show_post_path(post) %>
          <div><a><%= link_to 'Edit', edit_post_path(post.id) %></a></div>
          <div><a><%= link_to 'Delete', delete_post_path(post.id) %></a></div>
        </div>
      </div>
    </span>
  <% end %>

app/views/posts/edit.html.erb
<style>
  select {
      margin-right: 1rem;
      border: none;
      background-color: #F9FAFB;
      border-radius: 10px;
      outline-color: #F7F7F7;
      color: #666666;
  }

</style>

<div>
  <div style="padding: 39px; background-color: #F9FAFB; border-radius: 27px;">
    <div style="padding: inherit; border-radius: inherit; background-color: #FFFFFF" class="container-fluid">
      <%= form_with(model: @post, url: show_post_path ) do |post| %>
        <p>
          <%= post.text_area( :description, {:class => 'form-control', style: 'border-radius: 23px; height:290px'}) %>
        </p>

        <div class="d-flex">
          <div style="width: 100%">
            <%= post.select :status, ['public', 'private'], selected: 'public', class:'dropdown-menu' %>
          </div>
          <div class="d-flex" style="float: right">
            <%= post.submit('  Update  ',{:class => 'btn btn-primary'}) %><br>
            <!--<%#= link_to ' Update ', update_post_path(@post), method: :patch,:class => 'btn btn-primary' %><br>-->
            <%= link_to "Cancel", show_post_path , :class => "btn" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<style>
  .outline{
      border-color: #ffffff; !important;
      border-radius: 17px;
      color: #666666;
      font-family: "Cascadia Mono";
      font-weight: 600;
      text-align: left;
  }
</style>

  <div class>
    <div class="row align-items-start">
      <div class="col-1 bg-whtie p-2 me-lg-5">

        <!--Button-side-bar-->
        <div class='d-flex btn-group-vertical' style>
          <div class="container-fluid">
            <div style="align-content: flex-start; width: 11rem;">
                <%= render 'user/session_sidebar_manager' %>
            </div>
          </div>
        </div>

      </div>
      <div class="col-10 bg-white p-2" >
        <div style="margin-left: 2.5rem;padding: 9px; background-color: #F9FAFB; border-radius: 17px;">
        <div style='text-align:center'>
          <%= render 'layouts/pop_ups' %>
        </div>
          <div class="container-fluid" style="padding: 27px; border-radius: 16px">
            <%= render 'posts/post_menu' %>
            <%= render 'posts/all_posts' %>
          </div>
        </div>

      </div>
    </div>
  </div>

app/views/posts/show.html.erb
<style>
  .outline{
      border-color: #ffffff; !important;
      border-radius: 17px;
      color: #666666;
      font-family: "Cascadia Code";
      font-weight: 600;
      text-align: left;
  }
  button {
      border: none;
      background-color: #ffffff;
  }
</style>

  <div class>
    <div class="row align-items-start">
      <div class="col-1 bg-whtie p-2 me-lg-5">

        <!--Button-side-bar-->
        <div class='d-flex btn-group-vertical' style>
          <div class="container-fluid">
            <div style="align-content: flex-start; width: 11rem;">
                <%= render 'user/session_sidebar_manager', post: @post %>
            </div>
          </div>
        </div>

      </div>
      <div class="col-10 bg-white p-2" style="margin-left: 2.5rem" >

        <div style="padding: 40px; background-color: #F9FAFB; border-radius: 27px">
          <div style="background-color: white; border-radius: 17px">
            <div style="padding: 30px;">
              <div class="text-muted"> <!-- heading nahi banana hai (post_title)-->
                  <h5><%= image_tag('maze_logo.svg', style: 'margin-right:1rem') %>
                      <%= @post.user.first_name %></h5>
                  <small>
                    <%= time_ago_in_words(@post.created_at) %> ago
                    <small>&#8226</small>
                    <%= @post.status.to_str %>
                  </small>
                <%= render 'posts/three_dots_dropdown', post: @post %>
              </div>
              <br>
              <div>
                <p class="sed"><!--post_description-->
                  <%= @post.description %>
                </p>
              </div>
            </div>
            <br>
              <div style="margin-left: 32px; color: #60616599">
                <small><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></small>
                <small>&#8226</small>
                <small><%= render 'comments/comment_count', post: @post %></small>
            </div>
              <hr class="des"><!---------------------------------------------->
                <div class="d-flex" style="margin-left: 30px;">
                  <!--like_btn-->
                  <%= render 'likes/likings', likeable: @post %>
                  <!--comment_btn-->
                  <span style='margin-left: 15rem;' >
                    <%= link_to image_tag('comment.svg', style: 'width:30px') + "  Comments", show_post_path(@post) %>
                  </span>
                </div>
              <hr class="des"><!---------------------------------------------->
            <div class="container-fluid" style="padding-left: 31px; padding-right: 31px">
              <%= render 'comments/comment_menubar', post: @post %>
            </div>
            <h5 style="padding-top: 50px;padding-left: 28px;color: #60616599;">Comments</h5>
            <div class="container-fluid">
              <% @comments.order(created_at: :desc).each do |comment| %>
                <hr class><!---------------------------------------------->
                <div class="container-fluid" style="padding: 10px;">
                    <div style="padding-top: 10px; padding-bottom: 10px">
                      <%= render 'comments/comment_content', post: @post, comment: comment %>
                    </div>
                </div>
              <% end %><br>
            </div>
            </div>
        </div>
      </div>
    </div>
  </div>